### ISSUE TITLE
Dragging is fragmented(not continuous) on Sony X Compact

### ISSUE THREAD

**Issue by qqq89513** [toneiv/AutoCursor#24]
Hi, I have purchased a pro version of this app.
However, I found out that the dragging action is not performed as expected.

In [this video](https://drive.google.com/file/d/1L_Labb55S60iQzeigfgC6BoXGxlvjqEI/view), I first used the touch screen directly to show you that my touch screen works fine. Then I used AutoCursor to draw the same graph. When using AutoCursor, I found that the the *touch* was not persistent. It was like switching on and off. I also turned on the touch screen debug for more information.
And another bug I found is that the simulated touch and the cursor do not move together. You can see this from the above video and [this video](https://drive.google.com/file/d/1LYiLhqVRg1KyHsWUUpQ0TUc-d-sOKm7x/view?usp=sharing).

I really love this app and I think it's worth it to get a pro version. But this dragging issue keeps bothering me.
If you could fix this problem in short, I will definitely recommend this app to my friends who have big touch screens or partially malfunction touch area.

My phone:
```
Android 7.1.1
Sony X Compact (F5321)
No root
```
Let me know if you need more information.

**Comment by toneiv** [comment]
Hi,
Thank you for this very detailed ticket. 

I have not been able to reproduce this fragmentation problem but I think I have identified some weaknesses in my implementation that may explain this behaviour. An update will be available in the next few days. Can you tell me if it improves things on your device?

Regarding the second bug identified about the cursor and the simulated touch not always being in sync, I don't think I could improve things unfortunately. These are two processes running in parallel and implemented totally differently. It seems difficult to add checkpoints to synchronise the two. I'll make a note of the issue in case a workaround comes to mind.

**Comment by qqq89513** [comment]
Thanks for the reply and valuing this issue.
Looking forward to the update.
