### ISSUE TITLE
Adding option to disable cursor when keyboard is on

### ISSUE THREAD

**Issue by toneiv** [toneiv/AutoCursor#31]
Adding option to just disable cursor when keyboard is on. I've tried both Prevent side keyboard conflicts and Prevent bottom keyboard conflicts and neither works good if you have other side gestures on your phone.

**Comment by toneiv** [comment]
Done in 1.4.6

**Comment by Makstuff** [comment]
Is this option still in the app? I can't find it anywhere, and the two "Prevent keyboard conflicts" sliders don't seem to do anything for me.

**Comment by Makstuff** [comment]
Alright, I solved it by replicating my settings in Ubiki Touch instead. Wasn't aware it already contains the full features of AutoCursor. In UbikiTouch the full disable when keyboard is showing is available and works fine.

**Comment by toneiv** [comment]
Yes, this option is missing from Auto Cursor, it will be added in the next release. Thanks for pointing it out.
