### ISSUE TITLE
Option to make cursor disappear immediately after single autoclick?

### ISSUE THREAD

**Issue by Makstuff** [toneiv/AutoCursor#33]
I am using the app exclusively for single auto clicks, and I'm almost 100% happy with my current settings. I use autoclick at first release and make the cursor disappear after 1ms.

However in this case, the 1ms seems to only apply to the tracker, and the cursor lingers for about a second. I hope the video makes it clear what I mean. After clicking on the app, while the app is already opening, at 0:07 I can still see the cursor lingering over the grey background, which I find pretty distracting.

(I should mention that I have the tracker set to 100% transparency, which is why it is not visible.)

https://github.com/toneiv/AutoCursor/assets/57408125/308f5129-1f85-4d3b-b9be-02872e07ae29

**Comment by Makstuff** [comment]
Just for the record, I switched my cursor to Ubiki Touch for an independent reason explained in my comment on https://github.com/toneiv/AutoCursor/issues/31, but the behavior is exactly the same.

**Comment by toneiv** [comment]
This bug should be corrected in version 1.7.5 of Auto Cursor and version 1.13.7 of UbikiTouch.

**Comment by Makstuff** [comment]
Just updated. Tbh I would prefer the ability to remove the disapperance animation completely, which I dont think is possible (?), but its very usable as is. Thanks for the quick response anyway!

**Comment by toneiv** [comment]
I'll make a note of your request to deactivate the animation for a future update. Thank you for your feedback
